spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    username: alex
    password: alex
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092

  flyway:
    user: alex
    password: alex
    baseline-on-migrate: false
    enabled: true
    out-of-order: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:2000/eureka

cloud:
  aws:
    s3:
      bucket:
        name: reports
      path-style:
        enabled: "true"
      anonymous-files:
        enabled: "false"
    endpoint: http://minio:9000
    credentials:
      access-key: minioadmin
      secret-key: minioadmin

logging:
  level:
    org.springframework: info
    org.springframework.transaction: info
    org.springframework.kafka.transaction: info
    org.springframework.jdbc: info