server:
  port: 0

spring:
  application:
    name: master-service

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

  datasource:
    url: jdbc:postgresql://master-service-db:5432/reports

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.example.masterservice.serializers.ReportSerializer
      transaction-id-prefix: tx-master-

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.example.masterservice.serializers.ReportDeserializer
      enable-auto-commit: false
      properties:
        isolation_level: read-committed

logging:
  level:
    org.example.masterservice: info