server:
  port: 0

  application:
    name: master-service

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update

  datasource:
    url: jdbc:postgresql://localhost:5434/reports
    username: alex
    password: alex
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.example.masterservice.serializers.ReportSerializer
      transaction-id-prefix: tx-master-
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.example.masterservice.serializers.ReportDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      isolation-level: read_committed

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka

logging:
  level:
    org.springframework: info
    org.example.masterservice: info
    org.springframework.transaction: info
    org.springframework.kafka.transaction: info
    org.springframework.jdbc: debug