server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: master-service
          uri: lb://master-service/
          predicates:
            - Path=/master-service/**

        - id: worker-service
          uri: lb://worker-service/
          predicates:
            - Path=/worker-service/**

        - id: client-service
          uri: lb://client-service/
          predicates:
            - Path=/client-service/**
