server:
  port: 0

spring:
  application:
    name: client-service

  datasource:
    url: jdbc:postgresql://client-service-db:5432/clients

  flyway:
    url: jdbc:postgresql://client-service-db:5432/clients
