server:
  port: 0

spring:
  application:
    name: client-service

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://client-service-db:5432/clients
    username: alex
    password: alex
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://client-service-db:5432/clients
    user: alex
    password: alex
    baseline-on-migrate: false
    enabled: true
    out-of-order: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:2000/eureka
