server:
  port: 0
spring:
  application:
    name: client-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/clients
    username: alex
    password: alex
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://localhost:5432/clients
    user: alex
    password: alex
    baseline-on-migrate: false
    enabled: true
    out-of-order: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka
